service: task-management-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2  
  environment:
    TASKS_TABLE: !Ref TasksTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt TasksTable.Arn

functions:
  createTask:
    handler: functions/create.handler
    events:
      - http:
          path: tasks
          method: post
          cors: true

  listTasks:
    handler: functions/list.handler
    events:
      - http:
          path: tasks
          method: get
          cors: true

  getTask:
    handler: functions/get.handler
    events:
      - http:
          path: tasks/{id}
          method: get
          cors: true

  updateTask:
    handler: functions/update.handler
    events:
      - http:
          path: tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: functions/delete.handler
    events:
      - http:
          path: tasks/{id}
          method: delete
          cors: true

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-tasks-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

